### ISSUE TITLE
React Spinner Can not used similary if i use mui chart, full calendar etc. i am sharing the screenshot.

### ISSUE THREAD

**Issue by NileshJain82** [hoosierhuy/vite-react-server-side-render#1]
import BaseLayout from '../../components/layout/BaseLayout'
import { ClockLoader } from "react-spinner";
export const Home = (): JSX.Element => {
  return (
    <BaseLayout>
      <ClockLoader />

      <h3>Home</h3>
      Home, sweet home 🏠.
    </BaseLayout>
  )
}

this is the code sample i used and now i am getting this error.

![Screenshot from 2024-09-30 11-36-59](https://github.com/user-attachments/assets/0ef8785e-820b-40d3-8cd9-8f2bc12deb5a)

**Comment by NileshJain82** [comment]
is there any way by which i can use these packages and still have the ssr.

**Comment by hoosierhuy** [comment]
> is there any way by which i can use these packages and still have the ssr.

Yes, in your  `vite.config.ts` file, add this:
`export default defineConfig({
  plugins: [
    react(),
    cjsInterop({
      dependencies: ['react-spinners'],
    }),
  ],
})`

And then just import the the `react-spinners` library normally.

Further reading:
https://vike.dev/broken-npm-package#workaround

**Comment by hoosierhuy** [comment]
@NileshJain82 
I have created a separate branch with the solution for you here: https://github.com/hoosierhuy/vite-react-server-side-render/tree/with-react-spinner

Please give it a star if it works for you.

**Comment by NileshJain82** [comment]
I tried using your project and then added the mui date picker and getting the error :- |


This is the code for the home page :- 


import BaseLayout from '../../components/layout/BaseLayout'
import dayjs from 'dayjs';
import { DemoContainer, DemoItem } from '@mui/x-date-pickers/internals/demo';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { MobileDatePicker } from '@mui/x-date-pickers/MobileDatePicker';
import { DesktopDatePicker } from '@mui/x-date-pickers/DesktopDatePicker';
import { StaticDatePicker } from '@mui/x-date-pickers/StaticDatePicker';

export const Home = (): JSX.Element => {
  return (
    <BaseLayout>
      <h3>Home</h3>
      Home, sweet home 🏠.
      <ResponsiveDatePickers />
    </BaseLayout>
  )
}



function ResponsiveDatePickers() {
  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DemoContainer
        components={[
          'DatePicker',
          'MobileDatePicker',
          'DesktopDatePicker',
          'StaticDatePicker',
        ]}
      >
        <DemoItem label="Desktop variant">
          <DesktopDatePicker defaultValue={dayjs('2022-04-17')} />
        </DemoItem>
        <DemoItem label="Mobile variant">
          <MobileDatePicker defaultValue={dayjs('2022-04-17')} />
        </DemoItem>
        <DemoItem label="Responsive variant">
          <DatePicker defaultValue={dayjs('2022-04-17')} />
        </DemoItem>
        <DemoItem label="Static variant">
          <StaticDatePicker defaultValue={dayjs('2022-04-17')} />
        </DemoItem>
      </DemoContainer>
    </LocalizationProvider>
  );
}

and here's the vite config file.

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'

import { cjsInterop } from 'vite-plugin-cjs-interop'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    /**
     * https://vike.dev/broken-npm-package#workaround
     * Work around for:
     * SyntaxError: [vite] Named export 'ClockLoader' not found.
     * The requested module 'react-spinners' is a CommonJS module,
     * which may not support all module.exports as named exports.
     */
    cjsInterop({
      dependencies: ['react-spinners', "@mui/x-date-pickers", "mui/x-date-pickers"],
    }),
  ],
})

i tried both ways @mui/x-date-pickers and mui/x-date-pickers

 please look into the issue

**Comment by NileshJain82** [comment]
Hello buddy,

Clock loader is working fine. But while using the mui date picker in your
own repo's code i am not able to move ahead.
